sudo: true
language: python
python:
  - "2.7"
# command to install dependencies

before_install:
  - sudo sh install_travis.sh

install: pip install -r requirements_travis.txt
# command to run tests
script: sh run_travis.sh
