sudo: true
language: python
python:
  - "3.4"
# command to install dependencies

before_install:
  - sudo bash install_travis.sh

install: pip install -r requirements_travis.txt
# command to run tests
script: sh run_travis.sh
