sudo: true
language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies

before_install:
  - sudo sh install_travis.sh

install: sudo pip install onyxproject
# command to run tests
script: sudo onyxstart